version: "3.8"
services:
  backend:
    image: "hungpd170501/spring-react-example:2.4.2023.13.36.43"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev