version: "3.8"
services:
  backend:
    image: "hungpd170501/spring-react-example:7.4.2023.17.50.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev