version: "3.8"
services:
  backend:
    image: "hungpd170501/spring-react-example:19.4.2023.15.32.45"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev